spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://117.72.56.61:3306/jiaofu?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&noAccessToProcedureBodies=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://117.72.56.61:3306/jiaofu?serverTimezone=UTC&useSSL=true&allowPublicKeyRetrieval=true&autoReconnect=true&socketTimeout=60000&characterEncoding=utf-8
    username: jiaofu
    password: QAZ123_abc!
    hikari:
      connectionTestQuery: SELECT 1
      connectionTimeout: 30000
      idleTimeout: 300000
#      maxLifetime: 1740000
      maxLifetime: 1800000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: HikariPool-1
      registerMbeans: true
      validationTimeout: 5000
      leakDetectionThreshold: 30000
      keepalive-time: 60000
      initialization-fail-timeout: 1

  data:
    redis:
      host: 117.72.56.61
      port: 6379
      password: redis
      database: 1 # 默认值为0
      timeout: 10s
      connectTimeout: 5s
      lettuce:
        pool:
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0
  application:
    name: jiaofu

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ryqg.jiaofu.domain.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  session:
    type: jwt # 会话方式 jwt/redis-token
    access-token-time-to-live: 7200   # 访问令牌 有效期(单位：秒)，默认 2 小时，-1 表示永不过期
    refresh-token-time-to-live: 604800 # 刷新令牌有效期(单位：秒)，默认 7 天，-1 表示永不过期
    jwt:
      secret-key: SecretKey012345678901234567890123456789012345678901234567890123456789 # JWT密钥(HS256算法至少32字符)
      ttl: 20000
      tokenName: Authorization
    redis-token:
      allow-multi-login: true # 是否允许多设备登录
  # 安全白名单路径，仅跳过 AuthorizationFilter 过滤器，还是会走 Spring Security 的其他过滤器(CSRF、CORS等)
  ignore-urls:
    - /api/v1/auth/login/**       # 登录接口(账号密码登录、手机验证码登录和微信登录)
    - /api/v1/auth/refresh-token  # 刷新令牌接口
    - /api/v1/auth/logout         # 开放退出登录
    - /ws/**                      # WebSocket接口
    - /druid/**
    - /doc
    - /swagger-ui/**
    - /v3/api-docs/**
    - /webjars/**
    - /favicon.ico
    - /index.html
    - /actuator/**
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,info"
  endpoint:
    health:
      show-details: always